// Code generated by "stringer -type=nameErrors"; DO NOT EDIT.

package project

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[nameError-11]
}

const _nameErrors_name = "nameError"

var _nameErrors_index = [...]uint8{0, 9}

func (i nameErrors) String() string {
	i -= 11
	if i < 0 || i >= nameErrors(len(_nameErrors_index)-1) {
		return "nameErrors(" + strconv.FormatInt(int64(i+11), 10) + ")"
	}
	return _nameErrors_name[_nameErrors_index[i]:_nameErrors_index[i+1]]
}
